### ISSUE TITLE
Infinite loop with latest remix version

### ISSUE THREAD

**Issue by devstojko** [rphlmr/react-router-hono-server#2]
Hello there! 

I just tried to implement your package with existing project with instructions provided in Readme file and also checked example dir how it's done.

I have latest remix version 2.11.1 and after start dev server I got infinite loop of requests.
![image](https://github.com/user-attachments/assets/b495ef70-059b-4c82-b5d6-a3c5dc2b19fd)

Added new route /test and removed root loader to make sure that it's not something on my side. I saw that remix 2.11.0 introduced some infinite loop but they patched with 2.11.1 so I am not sure if that's somehow connected or not. 

Vite version is 5.3.5 and remix-hono 0.0.16

**Comment by rphlmr** [comment]
I have a pending PR to move the Remix dependency as a peer so it doesn't interfere (I only use types though). Do you see 2.11.0 in your package-lock or equivalent?

I will push this new version now if it helps.

**Comment by rphlmr** [comment]
npm i https://pkg.pr.new/rphlmr/react-router-hono-server@1 to test it if you want.

Remix hono and hono should not be mandatory in the future 0.0.3

**Comment by devstojko** [comment]
Check this out. Seems that remix-hono brings that 2.11.0 server runtime

![image](https://github.com/user-attachments/assets/63c3e871-7d50-4b1d-82ca-ae458de43fcc)

**Comment by rphlmr** [comment]
Check `"node_modules/@remix-run/server-runtime"` this is what has been resolved. I'm trying to force peers for `2.11.1` min

**Comment by devstojko** [comment]
Ok so: 

I removed remix-hono and hono as dependecies, added https://pkg.pr.new/rphlmr/react-router-hono-server@1  version, removed pnpm-lock / node_modules, fresh install and I can confirm that local dev is now working without infinite loop.

**Comment by rphlmr** [comment]
Wow, thanks. I’m finishing my PR and will release it next

**Comment by devstojko** [comment]
Just tested build and start, no issues so far! :)

I guess it will work also once I build in Docker and deploy it.

**Comment by rphlmr** [comment]
0.0.3 has been released!
https://github.com/rphlmr/react-router-hono-server/releases/tag/v0.0.3

I hope it definitely fixes the issue. Thanks for reporting it. 🫡
