### ISSUE TITLE
Bun: Action request fails if it lasts longer than 12 seconds.

### ISSUE THREAD

**Issue by lucasthevenet** [rphlmr/react-router-hono-server#27]
Hi there, I've been tinkering a little with the bun adapter and I encountered an issue with react router actions.

When the request for an action lasts a long time, the request gets cut off and fails with net::ERR_EMPTY_RESPONSE on the client side. From testing I've found it starts failing at 12 seconds.

To reproduce this error, you can just create a project using the bun example and add an action that lasts 12 seconds or more.

[Here is a link to a reproduction repo I've made](https://github.com/lucasthevenet/react-router-bun)

**Comment by rphlmr** [comment]
👋 hey

It is because Bun server as an idleTimeout of 10s or so.

You can customize that in the server.ts file.
```ts
// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/bun";

export default await createHonoServer({
  customBunServer: {
    idleTimeout: 60
  }
});
```

This file is not in your example but you can reveal it with
```sh
npx react-router-hono-server reveal file
```

**Comment by lucasthevenet** [comment]
I changed the idleTimeout and it worked! Thanks for the fast response.
