### ISSUE TITLE
Typecheck revealed server.ts

### ISSUE THREAD

**Issue by SmartArray** [rphlmr/react-router-hono-server#35]
Thank you for providing this package. It works out of the box! Really great work!!

Is there a way to make sure the revealed `server.ts` is typechecked? 

**Example:**

```typescript
// generated by react-router-hono-server/dev
import { createHonoServer } from 'react-router-hono-server/node';

const app = await createHonoServer({
  host: config.server.host,
  port: new Date('2024-12-12'), // Typescript does not complain about this
  defaultLogger: false,
  
  configure: async (server) => {
    server.get('/api/v1', (c) => {
      return c.text('Hello');
    });
  },

  listeningListener: (info) => {
    console.log(`Listening on interface ${info.address} at port ${info.port}`);
  },
});

export default app;

```

**Comment by rphlmr** [comment]
Thanks 🙏

It should 🧐

The screenshot comes from one of the examples.

![CleanShot 2024-12-19 at 21 37 49@2x](https://github.com/user-attachments/assets/9e711b46-5d59-4e5f-a665-7cffc396dd87)

**Comment by SmartArray** [comment]
Thanks! Closing this for now because I guess it's probably a user error and I am going to look into it soon
