### ISSUE TITLE
Export named 'renderToPipeableStream' not found in module

### ISSUE THREAD

**Issue by dayatwork** [rphlmr/react-router-hono-server#36]
Export named 'renderToPipeableStream' not found in module when using bun and react 19. But it works fine when using react 18.

**Comment by widiu7omo** [comment]
Yep. I have same issue with react 19. Hope will fix it soon

**Comment by rphlmr** [comment]
Looks like related to https://github.com/remix-run/react-router/issues/12568 🧐
