### ISSUE TITLE
Allow to modify the build output options

### ISSUE THREAD

**Issue by alessandrojcm** [rphlmr/react-router-hono-server#39]
Hi there!

Thanks for the great package, made mi migration from Remix a breeze. I just have a small issue. In my project, I have a bit of a special setup, during dev, I run a virtual module that loads a config file using `c12`; this works fine. 

However, during build, I wrap my Hono server with a `AsyncLocalStorage` hook. For this to work, I had a custom build config to make this work. Since this pluhin has its own build configuration around the Hono server, my config no longer works. Do you think we could add an extra option to the plugin, so users can provide their own `output` configuration? Happy to submit a PR if that suits.

Thanks!

**Comment by alessandrojcm** [comment]
Hm, on another look, I think I can just move everything to use Hono's [context storage middleware](https://hono.dev/docs/middleware/builtin/context-storage), so this might not be necessary after all.

**Comment by rphlmr** [comment]
Hey 👋

I am totally open to pull requests if you have a use case to support 🫡

I’d opt for a Hono middleware too. Let me know!

**Comment by alessandrojcm** [comment]
Great! I'll have a think on how go best go about it and make a pr if necessary

**Comment by alessandrojcm** [comment]
Manage to solve it from userland, so no need for a PR after all.
