### ISSUE TITLE
getConnInfo() throws an exception when running node in dev-mode

### ISSUE THREAD

**Issue by bravo-kernel** [rphlmr/react-router-hono-server#40]
As discussed on Discord, calling `getConnInfo()` throws this error when running node-server in dev-mode.

```
TypeError: Cannot read properties of undefined (reading 'socket')
    at getConnInfo (file:///D:/path-to/repo/node_modules/@hono/node-server/dist/conninfo.mjs:4:37)
```

As can be replicated by this simple middleware:

```ts
import { getConnInfo } from "@hono/node-server/conninfo";
import { createMiddleware } from "hono/factory";

export const localNetwork = createMiddleware(async (c, next) => {
  const info = getConnInfo(c) // info is `ConnInfo`
  console.log(`Remote address is ${info.remote.address}`)

  await next();
});
```

Possibly because we are running vite dev server in dev and therefore nothing is set in [c.env.server](https://github.com/honojs/node-server/blob/main/src/conninfo.ts).

**Comment by rphlmr** [comment]
Hey 👋

Should be good with https://github.com/rphlmr/react-router-hono-server/releases/tag/v2.4.0!
