### ISSUE TITLE
MAC OS Environment issue

### ISSUE THREAD

**Issue by sajidali2444** [rphlmr/react-router-hono-server#7]
I am getting errors while adding react-router-hono-server package using MAC os 
Couldn't find package "@rollup/rollup-darwin-x64-musl@4.18.1" required by "react-router-hono-server@^0.1.0"

**Comment by rphlmr** [comment]
👋 I am on macOS too and never encountered this issue.

I would like to reproduce it. Did you add react-router-hono-server on an existing Remix vite project or a new one?

What package manager do you use?

Can you try to delete your package manager lock file?

**Comment by rphlmr** [comment]
@AlemTuzlak did you encounter this issue with your package template?

**Comment by sajidali2444** [comment]
I just cloned @AlemTuzlak repository as it. and I am using yarn package manager.
node version 22.6.0
here is this screenshot
<img width="1619" alt="image" src="https://github.com/user-attachments/assets/59f6fa46-8651-406a-b6d4-d4a11a7b7f18">

I also remove package-lock file and yarn.lock file along with node_modules directory.
same error again

**Comment by sajidali2444** [comment]
now it is installed using npm i and it works but does not work with a yarn package manager.

**Comment by AlemTuzlak** [comment]
Rollup uses your current OS info to install one of like 20 potential rollup OS specific dependencies into the project like the rollup-darwin-x64-gnu one, and if another person tries to install them on an OS different than yours it usually doesn't work, this is especially true with windows/macos and hence why I always add them into optionalDependencies as that is a "hack" for this issue, although this specific one might be related to how yarn resolves these.
