### ISSUE TITLE
Couldn't find package "@rollup/rollup-darwin-x64-gnu@4.18.1" required by "react-router-hono-server" on the "npm" registry.

### ISSUE THREAD

**Issue by MiDonGo64** [rphlmr/react-router-hono-server#8]
When trying to install the package, I get the error "Couldn't find package "@rollup/rollup-darwin-x64-gnu@4.18.1" required by "react-router-hono-server" on the "npm" registry." I've tried multiple solutions but can only come to the determination that the package does not exist. 
It is these 3 that pop up and can not be found.

    "@rollup/rollup-darwin-x64-gnu": "4.18.1",
    "@rollup/rollup-darwin-x64-musl": "4.18.1",
    "@rollup/rollup-win32-x64-musl": "4.18.1"

**Comment by rphlmr** [comment]
👋 do you use yarn?

**Comment by rphlmr** [comment]
I have published version 0.2.0. Let me know how it goes.

**Comment by MiDonGo64** [comment]
I have it installed using 
```
yarn add rphlmr/react-router-hono-server#v0.2.0  
```
Thanks for the help.

**Comment by MiDonGo64** [comment]
When will the release publish to npmjs?

**Comment by rphlmr** [comment]
Oh sorry I thought it was. Should be good now
